### ISSUE TITLE
New mission/monster abilities

### ISSUE THREAD

**Issue by huldu** [Kvalyr/KayrCovenantMissions#4]
There are new missions and monster abilities in the new 9.1 patch and the addon doesn't know how to deal with them properly. One was a straight up does XX damage every 2 turns. Then I think another one was a basic damage reduction every X turns. It shouldn't be too hard to udate I hope.

**Comment by Kvalyr** [comment]
Thanks for the feedback.

This addon doesn't pay any attention to the specifics of monster/unit abilities, however; and never has. It just does a simple calculation based on the attack/defence numbers that Blizzard's own UI provides based on the units on the board.

This is by design, and means that this addon is simple; giving only conservative estimates of success/failure to guide the player, rather than complex simulations of the battles that risk being wrong and misguiding the player to failure.
